name: Generate Repo Content JSON

on:
  push:
    branches:
      - main

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate JSON
        run: |
          # List all directories (excluding public and src) in the repository and save the result to repoContent.json
          find . -type d -not -path "./public/*" -not -path "./src/*" -maxdepth 1 -mindepth 1 | sed 's/\.\///' > repoContent.json

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add repoContent.json
          git commit -m "Update repoContent.json" || echo "No changes to commit"
          git push
